
version: "3"

services:
   php:
      build: ./php
      depends_on:
         - mysql
      env_file:
         - ./docker-compose-lesson.env
      environment:
         - MYSQL_HOST=mysql
   ng:
      build: ./ng
      depends_on:
         - php
      ports:
         - 80:80
   mysql:
      build: ./mysql
      env_file:
         - ./docker-compose-lesson.env
      ports:
         - 33006:3306